config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PTsolvers/JustRelax.jl:
      branch: main
      repo: https://github.com/PTsolvers/JustRelax.jl
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-rose-beagle.sh
        container: qc.acc_wheezy-beige-binturong
  QC.Doc:
    repos:
      github.com/PTsolvers/JustRelax.jl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-scarlet-caracal.sh
        container: qc.doc_gamy-platinum-buffalo
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-firebrick-ibis.sh
        container: qc.doc_greasy-pink-orangutan
      github.com/PTsolvers/JustRelax.jl markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-beige-mule.sh
        container: qc.doc_slimy-coral-rat
  QC.Lic:
    repos:
      github.com/PTsolvers/JustRelax.jl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-peach-coyote.sh
        container: qc.lic_sloppy-persimmon-angelfish
  QC.Ver:
    repos:
      github.com/PTsolvers/JustRelax.jl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-pear-birman.sh
        container: qc.ver_sickly-white-devil
timeout: 5400
