config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PTsolvers/JustRelax.jl:
      branch: main
      repo: https://github.com/PTsolvers/JustRelax.jl
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-celadon-affenpinscher.sh
        container: qc.acc_cheeky-harlequin-wrasse
  QC.Doc:
    repos:
      github.com/PTsolvers/JustRelax.jl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-puce-bonobo.sh
        container: qc.doc_leaky-lime-lionfish
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-olivine-badger.sh
        container: qc.doc_sleepy-ochre-chimpanzee
  QC.Lic:
    repos:
      github.com/PTsolvers/JustRelax.jl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-pumpkin-vulture.sh
        container: qc.lic_foggy-orchid-capybara
  QC.Met:
    repos:
      github.com/PTsolvers/JustRelax.jl cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cardinal-fowl.sh
        container: qc.met_scaly-cornflower-spider
  QC.Ver:
    repos:
      github.com/PTsolvers/JustRelax.jl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-beige-sloth.sh
        container: qc.ver_chewy-ochre-starfish
timeout: 5400
