config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PTsolvers/JustRelax.jl:
      branch: main
      repo: https://github.com/PTsolvers/JustRelax.jl
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-lime-quail.sh
        container: qc.acc_surly-scarlet-quoll
  QC.Doc:
    repos:
      github.com/PTsolvers/JustRelax.jl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-brass-newt.sh
        container: qc.doc_wiggy-lemon-whale
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-teal-labradoodle.sh
        container: qc.doc_pretty-malachite-rhinoceros
      github.com/PTsolvers/JustRelax.jl markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aqua-devil.sh
        container: qc.doc_sickly-persimmon-giraffe
  QC.Lic:
    repos:
      github.com/PTsolvers/JustRelax.jl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-razzmatazz-wolverine.sh
        container: qc.lic_geeky-amethyst-wrasse
  QC.Met:
    repos:
      github.com/PTsolvers/JustRelax.jl cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homely-ecru-spider.sh
        container: qc.met_randy-purple-harrier
  QC.Ver:
    repos:
      github.com/PTsolvers/JustRelax.jl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-burgundy-kangaroo.sh
        container: qc.ver_fuzzy-aquamarine-mammoth
timeout: 5400
