config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PTsolvers/JustRelax.jl:
      branch: main
      repo: https://github.com/PTsolvers/JustRelax.jl
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-olivine-lemming.sh
        container: qc.acc_blurry-chartreuse-dhole
  QC.Doc:
    repos:
      github.com/PTsolvers/JustRelax.jl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-chestnut-rhinoceros.sh
        container: qc.doc_hasty-buff-octopus
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ochre-echidna.sh
        container: qc.doc_flimsy-carmine-devil
      github.com/PTsolvers/JustRelax.jl markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-tomato-whippet.sh
        container: qc.doc_grumpy-ivory-corgi
  QC.Lic:
    repos:
      github.com/PTsolvers/JustRelax.jl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-amethyst-serval.sh
        container: qc.lic_wiggy-thistle-avocet
  QC.Ver:
    repos:
      github.com/PTsolvers/JustRelax.jl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-emerald-saola.sh
        container: qc.ver_flimsy-cobalt-tortoise
timeout: 5400
