config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PTsolvers/JustRelax.jl:
      branch: main
      repo: https://github.com/PTsolvers/JustRelax.jl
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-aquamarine-centipede.sh
        container: qc.acc_messy-cobalt-terrier
  QC.Doc:
    repos:
      github.com/PTsolvers/JustRelax.jl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-taupe-turtle.sh
        container: qc.doc_nerdy-apricot-bat
      github.com/PTsolvers/JustRelax.jl git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-teal-sheepdog.sh
        container: qc.doc_geeky-lilac-goose
  QC.Lic:
    repos:
      github.com/PTsolvers/JustRelax.jl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-salmon-badger.sh
        container: qc.lic_freaky-corn-jackal
  QC.Ver:
    repos:
      github.com/PTsolvers/JustRelax.jl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-mustard-kudu.sh
        container: qc.ver_sleepy-gamboge-armadillo
timeout: 5400
